sudo: required女弓弓弓弓弓
service:
 - docker

before_script:
 - mkdir -pv ~/.docker
 - wget https://github.com/TravisLi/mastery-back-end/raw/Travis_CI/cert/cert.zip
 - unzip cert.zip -d ~/.docker
 - export DOCKER_HOST=tcp://coolki.myqnapcloud.com:2376
 - export DOCKER_CERT_PATH=~/.docker
 - export DOCKER_API_VERSION=1.23
 
script:
 - docker build -t mastery-back-end .
 
after_success:
 - docker login -u="$docker_username" -p="$docker_password" --tlsverify coolki.myqnapcloud.com
 - docker push mastery-back-end