sudo: required

language: java

service:
 - docker

before_script:
 - mkdir -pv ~/.docker
 - wget https://github.com/TravisLi/mastery-back-end/raw/Travis_CI/cert/cert.zip
 - unzip cert.zip -d ~/.docker
 
script:
 - docker build -t mastery-back-end .
 
after_success:
 - export DOCKER_HOST=tcp://coolki.myqnapcloud.com:2376 DOCKER_TLS_VERIFY=1
 - export DOCKER_CERT_PATH=~/.docker
 - export DOCKER_API_VERSION=1.23
 - docker tag mastery-back-end mastery-back-end:latest
 - docker push mastery-back-end:latest